# Created using wingetcreate 1.0.4.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultLocale.1.1.0.schema.json

PackageIdentifier: Zoom.Zoom.PluginforCitrixReceiver
PackageVersion: 5.10.21295
PackageLocale: en-US
Publisher: Zoom Video Communications, Inc.
PackageName: Zoom Plugin for Citrix Receiver
License: Proprietary Software / Freemium
ShortDescription: Zoom creates an optimized experience by sending independent data streams to both the VDI Client and plugin, allowing each component to focus on the responsibilities it does best.
ManifestType: defaultLocale
ManifestVersion: 1.1.0

